# Generated by Django 4.1.4 on 2024-05-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registration_id',
        ),
    ]
