# Generated by Django 5.0.4 on 2024-04-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New Connection', 'New Connection'), ('Installation', 'Installation'), ('Repair', 'Repair'), ('Inspection', 'Inspection'), ('Booking', 'Booking')], default='New Connection', max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Request Pending', 'Request Pending'), ('Request Resolved', 'Request Resolved')], default='Request Pending', max_length=30)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='service_request_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
